### ISSUE TITLE
SyntaxError: Unexpected token

### ISSUE THREAD

**Issue by soujiro0725** [aws-samples/aws-cloudwatch-snapshot-graphs-alert-context#2]
Thanks for such a wonderful code.  But I got the following error.
Do you have any idea what I did wrong?  It appears though there is something wrong with json data inserted into emailer.js.  Since I am a python person rather than node.js, any help will be appreciated.

`
2018-10-24T22:02:07.325Z 725ac861-d7d8-11e8-9e05-97b47dd9afb0 SyntaxError: Unexpected token e in JSON at position 0
at Object.parse (native)
at exports.myHandler (/var/task/emailer.js:43:26)
`

**Comment by lannyho** [comment]
have you changed the default handler into emailer.myHandler, like this

![image](https://user-images.githubusercontent.com/745623/47480090-cac2ee00-d861-11e8-94bf-4d21c5d80ca7.png)

**Comment by soujiro0725** [comment]
Yes. I have.

![2018-10-25 15 28 51](https://user-images.githubusercontent.com/1930972/47480233-b2a39c80-d86a-11e8-8f14-33b3889d7a78.png)

**Comment by lannyho** [comment]
I modified his code last two week, I changed something since I run this lambda function in Singapore region, may be you can try the following setting

1. Create a IAM user and have SES permission
2. Base on this IAM user, create a access key, this is for access SES service purpose
3. Modify the codes as below
![image](https://user-images.githubusercontent.com/745623/47480757-019a0380-d864-11e8-894b-dca7aad77ed8.png)

![image](https://user-images.githubusercontent.com/745623/47480852-4faf0700-d864-11e8-8eed-03ee4c02b488.png)

![image](https://user-images.githubusercontent.com/745623/47480896-7a995b00-d864-11e8-8e01-0284b365eba7.png)

Hope can help you.

**Comment by lannyho** [comment]
I am not sure the value of variable EMAIL_FROM_ADDRESS can execute this lambda function, I tried to registered email address which places in variable EMAIL_FROM_ADDRESS and EMAIL_TO_ADDRESS for testing....

ganbatte kudasai

**Comment by wisemanIV** [comment]
Hi, please can you add logging for the event variable to line 42 and paste what is in the SNS message? Console.log()

**Comment by soujiro0725** [comment]
I added `console.log(event);`  to line 42, and this is what I got by running a test.

`
START RequestId: 5862e2da-df0b-11e8-bcc9-3776071a08f3 Version: $LATEST
2018-11-03T01:54:06.361Z	5862e2da-df0b-11e8-bcc9-3776071a08f3	{ Records: 
   [ { EventSource: 'aws:sns',
       EventVersion: '1.0',
       EventSubscriptionArn: 'arn:aws:sns:ap-northeast-1:546666693273:plant-status-log',
       Sns: [Object] } ] }
2018-11-03T01:54:06.402Z	5862e2da-df0b-11e8-bcc9-3776071a08f3	SyntaxError: Unexpected token e in JSON at position 0
    at Object.parse (native)
    at exports.myHandler (/var/task/emailer.js:43:26)
END RequestId: 5862e2da-df0b-11e8-bcc9-3776071a08f3
`

**Comment by wisemanIV** [comment]
Please can you paste the Sns object - console.log(JSON.stringify(event.Records[0].Sns));

**Comment by soujiro0725** [comment]
Thanks for your response.

This is what I got by adding the code you specified.

`
START RequestId: f3794250-e155-11e8-ab9d-4545a4d78f85 Version: $LATEST
2018-11-05T23:53:11.512Z	f3794250-e155-11e8-ab9d-4545a4d78f85	{"Type":"Notification","MessageId":"95df01b4-ee98-5cb9-9903-4c221d41eb5e","TopicArn":"arn:aws:sns:ap-northeast-1:123456789012:ExampleTopic","Subject":"example subject","Message":"example message","Timestamp":"2018-10-22T00:00:00.000Z","SignatureVersion":"1","Signature":"EXAMPLE","SigningCertUrl":"EXAMPLE","UnsubscribeUrl":"EXAMPLE","MessageAttributes":{"Test":{"Type":"String","Value":"TestString"},"TestBinary":{"Type":"Binary","Value":"TestBinary"}}}
2018-11-05T23:53:11.530Z	f3794250-e155-11e8-ab9d-4545a4d78f85	SyntaxError: Unexpected token e in JSON at position 0
    at Object.parse (native)
    at exports.myHandler (/var/task/emailer.js:43:26)
END RequestId: f3794250-e155-11e8-ab9d-4545a4d78f85
REPORT RequestId: f3794250-e155-11e8-ab9d-4545a4d78f85	Duration: 79.62 ms	Billed Duration: 100 ms 	Memory Size: 128 MB	Max Memory Used: 39 MB	
RequestId: f3794250-e155-11e8-ab9d-4545a4d78f85 Process exited before completing request
`

**Comment by wisemanIV** [comment]
Hi, this doesn't look like it came from a CloudWatch alarm? You need to create a CloudWatch alarm that targets the SNS topic.

**Comment by wisemanIV** [comment]
This doesn't look like an issue with the sample, so I'm closing this issue.
